// SPDX-FileCopyrightText: Red Hat Inc
// SPDX-License-Identifier: LGPL-2.1-or-later

BLKSUM(1)
=========
:doctype: manpage

NAME
----

blksum - compute message digest for disk images

SYNOPSYS
--------

*blksum* [-d DIGEST|--digest=DIGEST] [-p|--progress]
         [-c|--cache] [-t N|--threads=N] [-S N|--streams=N]
         [--queue-depth=N] [--read-size=N]
         [-l|--list-digests] [-h|--help]
         ['FILENAME']

DESCRIPTION
-----------

blksum print a checksum for disk image guest visible content. You can
compare the checksum for disk images in 'raw' or 'qcow2' format. 'qcow2'
format is supported only if 'blksum' was built with NBD support.

The default digest is 'sha256'. Use '--digest' to select another digest
name. You can use any message digest name supported by openssl. Use
'--list-digests' to list the available digest names.

'FILENAME' can be a file or a NBD URL.

If 'FILENAME' is not specified, read data from standard input. This can
be used only for 'raw' images.

OPTIONS
-------

*-d, --digest*='DIGEST'::
  Select message digest algorithm supported by openssl. If not specified
  'sha256' is used.

*-p, --progress*::
  Show progress bar when computing a checksum.

*-c, --cache*::
  Use host page cache. This may be faster, but is not correct when using
  a block device connected to multiple hosts. Typically it gives less
  consistent results. If not set, enabled if the file system does not
  support direct I/O.

*--threads*='N'::
  Number of threads computing the checksum in parallel. The default
  value (4) is good enough for most cases. If your storage is very fast
  you can speed up checksum computation by increasing this value. The
  value must be smaller or equal to the number of streams. For best
  performance, the value should be power of 2.

*--streams*='N'::
  Number of hash streams, enabling parallel hashing. The deffault value
  (64) allows up to 64 threads. If you want to use more threads you need
  to increase this value. Note that changing this value changes the hash
  value and the computed hash will not be compatible with other users of
  the tool. The value must be equal or larger than the number of
  threads. For best performance, the value should be power of 2.

*--queue-depth*='N'::
  Maximum number of in-flight reads. The default value (16) gives best
  performance in most cases. If not set, the value will be optimized for
  the image format and file system type.

*--read-size*='N'::
  Maximum read size in bytes. The default value (256 KiB) gives best
  performance in most cases. If not set, the value will be optimized for
  the image format and file system type.

*-h, --help*::
  Show online help and exit.

*-l, --list-digests*::
  Print available digest names and exit.

EXAMPLES
--------

`blksum disk.qcow2`::
    Print a sha256 checksum for disk.qcow2.

`blksum --digest blake2b512 nbd+unix:///?socket=/tmp/nbd.sock`::
    Print a blake2b checksum for and image exported via NBD server.

`blksum <disk.img`::
    Print a sha256 checksum for data read from standard input.

AUTHORS
-------

Nir Soffer <nirsof@gmail.com>

COPYRIGHT
---------

Copyright Red Hat Inc.

LICENSE
-------

LGPL-2.1-or-later.

SEE ALSO
--------

openssl(1)
