# SPDX-FileCopyrightText: Red Hat Inc
# SPDX-License-Identifier: LGPL-2.1-or-later

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.test:
  script:
  - meson setup build
  - meson compile -C build
  - meson test -C build -v
  - ./build-rpms
  - dnf install -y build/rpm/RPMS/*/*.rpm

fedora-35:
  extends: .test
  image: quay.io/nirsof/blkhash-fedora-35

centos-8:
  extends: .test
  image: quay.io/nirsof/blkhash-centos-8

centos-9:
  extends: .test
  image: quay.io/nirsof/blkhash-centos-9
