# SPDX-FileCopyrightText: Red Hat Inc
# SPDX-License-Identifier: LGPL-2.1-or-later

variables:
  GIT_SUBMODULE_STRATEGY: recursive

workflow:
  rules:
    # To enable this workflow, add a variable in Settings > CI/CD > Variables.
    - if: $CI_ENABLED != "yes"
      when: never
    # See https://docs.gitlab.com/ee/ci/jobs/job_control.html#common-if-clauses-for-rules
    # https://docs.gitlab.com/ee/ci/yaml/workflow.html#switch-between-branch-pipelines-and-merge-request-pipelines
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_OPEN_MERGE_REQUESTS == null
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"

.test:
  script:
    - meson setup build -Dwerror=true
    - meson compile -C build
    - meson test -C build -v
    - ./build-rpms
    - mkdir rpms
    - mv build/rpm/RPMS/*/*.rpm rpms
    - dnf install -y rpms/*.rpm
  artifacts:
    name: $CI_JOB_NAME
    paths:
      - rpms

fedora-37:
  extends: .test
  image: quay.io/nirsof/blkhash-test:fedora-37

fedora-38:
  extends: .test
  image: quay.io/nirsof/blkhash-test:fedora-38

centos-8:
  extends: .test
  image: quay.io/nirsof/blkhash-test:centos-8

centos-9:
  extends: .test
  image: quay.io/nirsof/blkhash-test:centos-9
