// SPDX-FileCopyrightText: Red Hat Inc
// SPDX-License-Identifier: LGPL-2.1-or-later

BLKSUM(1)
=========
:doctype: manpage

NAME
----

blksum - compute message digest for disk images

SYNOPSYS
--------

*blksum* [-d DIGEST|--digest=DIGEST] [-w N|--workers=N]
         [-p|--progress] [-c|--cache] [--queue-size=N]
         [--read-size=N] [-l|--list-digests] [-h|--help]
         ['FILENAME']

DESCRIPTION
-----------

blksum print a checksum for disk image guest visible content. You can
compare the checksum for disk images in 'raw' or 'qcow2' format. 'qcow2'
format is supported only if 'blksum' was built with NBD support.

The default digest is 'sha256'. Use '--digest' to select another digest
name. You can use any message digest name supported by openssl. Use
'--list-digests' to list the available digest names.

'FILENAME' can be a file or a NBD URL.

If 'FILENAME' is not specified, read data from standard input. This can
be used only for 'raw' images.

OPTIONS
-------

*-d, --digest*='DIGEST'::
  Select message digest algorithm supported by openssl. If not specified
  'sha256' is used.

*-w, --workers*='N'::
  Set the number of workers. The default (4) gives good performance for
  fast digest like sha1. For slower digest like sha256 larger number of
  workers improves performance. The valid value is 1 up to the number of
  online cpus but not more than 16.

*-p, --progress*::
  Show progress bar when computing a checksum.

*-c, --cache*::
  Use host page cache. This may be faster, but is not correct when using
  a block device connected to multiple hosts. Typically it gives less
  consistent results. If not set, enabled if the file system does not
  support direct I/O.

*--queue-size*='N'::
  Maximum number of bytes to queue for in-flight reads. The default
  value (2 MiB) gives best performance in most cases. If not set, the
  value will be optimized for the image format and file system type.

*--read-size*='N'::
  Maximum read size in bytes. The default value (256 KiB) gives best
  performance in most cases. If not set, the value will be optimized for
  the image format and file system type.

*-h, --help*::
  Show online help and exit.

*-l, --list-digests*::
  Print available digest names and exit.


USING QEMU-NBD
--------------

For best performance when exporting images via 'qemu-nbd(8)' set the
'--shared' option to value equal or larger than the number of workers.
For example if using 4 workers, use:

    qemu-nbd --shared 4 -t -r -k /tmp/nbd.sock -f qcow2 disk.qcow2

EXAMPLES
--------

`blksum disk.qcow2`::
    Print a sha256 checksum for disk.qcow2.

`blksum --digest blake2b512 nbd+unix:///?socket=/tmp/nbd.sock`::
    Print a blake2b checksum for and image exported via NBD server.

`blksum <disk.img`::
    Print a sha256 checksum for data read from standard input.

AUTHORS
-------

Nir Soffer <nirsof@gmail.com>

COPYRIGHT
---------

Copyright Red Hat Inc.

LICENSE
-------

LGPL-2.1-or-later.

SEE ALSO
--------

qemu-nbd(8), openssl(1)
