version: 2.1

jobs:
  test:
    parameters:
      distro:
        type: string
    docker:
      - image: quay.io/nirsof/blkhash-test:<< parameters.distro >>
    steps:
      - checkout
      - run: meson setup build -Dwerror=true
      - run: meson compile -C build
      - run: meson test -C build -v
      - run: ./build-rpms
      - run: mkdir rpms
      - run: mv build/rpm/RPMS/*/*.rpm rpms
      - run: dnf install -y rpms/*.rpm

workflows:
  ci:
    jobs:
      - test:
          matrix:
            parameters:
              distro:
                - centos-9
                - fedora-40
                - fedora-41
                - fedora-42
